/*
- oya diisini ada pengecekan pathname
- jika berada di url yang di tentukan, navbar di tampilkan 
- ada penentuan font juga secara global
- metadata di matikan karena use client solusinya meta data dibuat pada templete mungkin nanti

*/

"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import Navbar from "./navbar";
import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });
// import fonts > gunakan classname pada body
// cek nextjs > doc > keyword: fonts, disana ada script pengganti fonts > gampang
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const disabledNavbar = ["/login", "/register"];

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className={poppins.className}>
        <SessionProvider>
          {!disabledNavbar.includes(pathname) && <Navbar />}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
